const JWT_ACCESS_EXPIRATION = process.env.JWT_ACCESS_EXPIRATION || '2d';
const JWT_REFRESH_EXPIRATION = process.env.JWT_REFRESH_EXPIRATION || '7d';
const JWT_ACCESS_SECRET = process.env.JWT_ACCESS_SECRET || 'yes@secret';
const JWT_REFRESH_SECRET = process.env.JWT_REFRESH_SECRET || 'no@secret';
const OTP_EXPIRATION_TIME = process.env.OTP_EXPIRATION_TIME || 5;

module.exports = {
  JWT_ACCESS_EXPIRATION,
  JWT_REFRESH_EXPIRATION,
  JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET,
  OTP_EXPIRATION_TIME,
};
